name: Demo for python

on:
  push:
     branches: [master]

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Set-up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest
        
  create_container:
    name: Create container and push to docker.io
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKEHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: justaway86/test-actions:latest
          
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: [create_container]
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host yandex_server
            HostName ${{ secrets.SERVER_IP }}
            User justaway
            IdentifyFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
      - name: Get code from repo
        uses: actions/checkout@v3
        
      - name: Rsync docker-compose file
        run: rsync -rav --delete docker-compose.yml yandex_server:~/
        
      - name: Run compose up
        run: ssh yandex_server 'sudo docker-compose up'
